apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_lhORZNnbY0z7@ep-weathered-breeze-ah653ejh-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  OPENAI_API_KEY: "AIzaSyBnVoKnhbMLtlBJw3lfup52hXAkhhB1KlU"
  BETTER_AUTH_SECRET: "your_better_auth_secret_here"
